# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170712_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([]),
        ),
    ]
