version: '3.7'

services:
  traefik:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=${EMAIL_FOR_LETSENCRYPT}"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --workers 2 --threads=4 --worker-tmp-dir /dev/shm --log-level info --log-file=- portanizer.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #  - ./:/usr/src/app/
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
      - "traefik.http.routers.web.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=https_redirect"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web-sec.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.routers.web-sec.entrypoints=websecure"
      - "traefik.http.routers.web-sec.tls.certresolver=myhttpchallenge"
  db:
    image: postgres:9.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

volumes:
  postgres_data:
