version: '3.3'

services:
  web:
    image: portanizer_web:latest
    entrypoint: ./entrypoint-prod.sh
    command: gunicorn --workers 2 --threads=4 --worker-tmp-dir /dev/shm --log-level info --log-file=- portanizer.wsgi:application --bind 0.0.0.0:8000
    networks:
      - default
      - traefik-public
    env_file:
      - .env
    deploy:
      labels:
        - traefik.frontend.rule=Host:portanizer.${DOMAIN?Variable DOMAIN not set}
          #- "traefik.backend=portanizer-web"        
        - traefik.enable=true
        - traefik.port=8000
        - traefik.docker.network=traefik-public
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        # - traefik.frontend.auth.basic.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}

  db:
    image: postgres:9.4-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    networks:
      - default

volumes:
  data:

networks:
  traefik-public:
    external: true
