---
apiVersion: v1
kind: Pod
metadata:
  labels:
    label: kube-slave-python
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  containers:
  - name: jnlp
    image: dimdiden/jenkins-slave:jdk11
    tty: true
    workingDir: /home/jenkins/agent
  - name: docker
    image: docker:latest
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock